  #spring.application.name=oms-product-service

  server:
    port: 8082

  spring:
    application:
        name: oms-product-service

    datasource:
        url: jdbc:postgresql://postgres-product:5432/oms_product_db
        username: postgres
        password: admin
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
          hibernate:
            format_sql: true

    redis:
        host: localhost
        port: 6379
        timeout: 2000


  logging:
    level:
      root: INFO
      com.oms.product: DEBUG